### PR TITLE
Opt in looker for GitHub app authentication

### PR DESCRIPTION
**Pull request by chaodaiG**
Looker had already installed the app https://github.com/apps/google-oss-prow, so this PR would work out of box.

Note that there will be some minor impacts:
1. there will be a few seconds that webhooks are double handled, so prow might do something repeatedly
2. prow will not recognize the comments it left before, so on existing PRs there will be two prow comments instead of one

### CODE REVIEW

**Comment by chaodaiG** [comment]
/assign @cjwagner 
cc @2nd-half

**Review by cjwagner — APPROVED** [review]
/hold

**Review by cjwagner — APPROVED** [review]
/hold

**Comment by chaodaiG** [comment]
/unhold
🤞

**Pull request merged**
