### PR TITLE
touch the oss-test-infra config

### PR DESCRIPTION
**Pull request by krzyzacy**
gcp-oss-test-infra-config.yaml looks odd..

```
senlu@senlu:~/work/src/github.com/GoogleCloudPlatform/oss-test-infra/prow$ kubectl get cm job-config -o yaml
apiVersion: v1
data:
  gcp-guest-config.yaml: |
    presubmits:
      GoogleCloudPlatform/osconfig:
        - name: osconfig-presubmit-gocheck
          cluster: gcp-guest
          agent: kubernetes
          run_if_changed: ".*\\.go$"
          trigger: "(?m)^/gocheck$"
          rerun_command: "/gocheck"
          context: prow/presubmit/gocheck
          spec:
            containers:
              - image: gcr.io/compute-image-tools-test/gocheck:latest
                volumeMounts:
                  - name: compute-image-tools-test-service-account
                    mountPath: /etc/compute-image-tools-test-service-account
                    readOnly: true
                volumes:
                  - name: compute-image-tools-test-service-account
                    secret:
                      secretName: compute-image-tools-test-service-account
        - name: osconfig-presubmit-gobuild
          cluster: gcp-guest
          agent: kubernetes
          run_if_changed: ".*\\.go$"
          trigger: "(?m)^/gobuild$"
          rerun_command: "/gobuild"
          context: prow/presubmit/gobuild
          spec:
            containers:
              - image: gcr.io/compute-image-tools-test/gobuild:latest
                volumeMounts:
                  - name: compute-image-tools-test-service-account
                    mountPath: /etc/compute-image-tools-test-service-account
                    readOnly: true
                volumes:
                  - name: compute-image-tools-test-service-account
                    secret:
                      secretName: compute-image-tools-test-service-account

    periodics:
    - name: cluster-gcp-guest
      cluster: gcp-guest
      interval: 30m
      decorate: true
      spec:
        containers:
        - image: alpine
          command: ["/bin/date"]
  gcp-oss-test-infra-config.yaml: "presubmits:\n  GoogleCloudPlatform/oss-test-infra:\n
    \ - name: pull-prow-config-validate\n    branches:\n    - master\n    decorate:
    true\n    always_run: true\n    extra_refs:\n    - org: kubernetes\n      repo:
    test-infra\n      base_ref: master\n      path_alias: k8s.io/test-infra\n    spec:\n
    \     containers:\n      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190329-811f7954b-master\n
    \       command:\n        - runner.sh \n        args:\n        - bash\n        -
    -c\n        - >-\n          cd /home/prow/go/src/k8s.io/test-infra &&\n          bazel
    run prow/cmd/checkconfig -- --config-path=/home/prow/go/src/github.com/GoogleCloudPlatform/oss-test-infra/prow/config.yaml\n\nperiodics:\n#
    test jobs, remove later\n- name: cluster-unspecified\n  # cluster:\n  interval:
    30m\n  decorate: true\n  spec:\n    containers:\n    - image: alpine\n      command:
    [\"/bin/date\"]\n- name: cluster-default\n  cluster: default\n  interval: 30m\n
    \ decorate: true\n  spec:\n    containers:\n    - image: alpine\n      command:
    [\"/bin/date\"]"
  kunit-linux-config.yaml: |
    presubmits:
      https://kunit-review.googlesource.com/linux:
      - name: kunit-test-presubmit
        branches:
        - kunit/alpha/master
        decorate: true
        always_run: true
        spec:
          volumes:
          - name: shared-mem
            emptyDir: {}
          containers:
          - image: gcr.io/kunit-presubmit/kunit
            securityContext:
              privileged: true
            command:
            - /kunit.sh
            volumeMounts:
            - name: shared-mem
              mountPath: /dev/shm
kind: ConfigMap
metadata:
  creationTimestamp: 2019-04-26T22:54:55Z
  name: job-config
  namespace: default
  resourceVersion: "27876455"
  selfLink: /api/v1/namespaces/default/configmaps/job-config
  uid: 4ee73507-6876-11e9-9c43-42010a8a027c

```

### CODE REVIEW

**Comment by krzyzacy** [comment]
test tide, and see if config-updater can fix it

**Comment by krzyzacy** [comment]
{"component":"tide","error":"prowjobs.prow.k8s.io is forbidden: User \"system:serviceaccount:default:default\" cannot list prowjobs.prow.k8s.io in the namespace \"default\"","level":"error","msg":"Error syncing.","time":"2019-04-30T21:40:28Z"}

/shrug

**Comment by krzyzacy** [comment]
@cjwagner have you seen this behavior before from config-bootstrapper...

**Comment by cjwagner** [comment]
@krzyzacy No I haven't. Maybe there is something wrong with the file itself?

**Comment by krzyzacy** [comment]
hummmm the periodics are running, so I guess that's not the actual problem

**Pull request merged**
