### PR TITLE
Removed kubeflow-pipeline-upgrade-test from Kubeflow Pipelines tests

### PR DESCRIPTION
**Pull request by hbelmiro**
Removing kubeflow-pipeline-upgrade-test due to https://github.com/kubeflow/pipelines/pull/10932.

cc @chensun

### CODE REVIEW

**Comment by hbelmiro** [comment]
cc @chensun @zijianjoy @james-jwu

**Comment by hbelmiro** [comment]
@james-jwu can you help me to get this approved?

**Review by chensun — COMMENTED** [review]
/lgtm
/approve

**Comment by hbelmiro** [comment]
@chensun I had to rebase.
Can you please take a second look and `/ok-to-test`?

**Pull request merged**
