### PR TITLE
Adding GoogleCloudPlatform/netd (moving from Kubernetes's Prow)

### PR DESCRIPTION
**Pull request by jingyuanliang**
Fixes https://github.com/GoogleCloudPlatform/netd/issues/128.

### CODE REVIEW

**Comment by chases2** [comment]
What order should this and https://github.com/kubernetes/test-infra/pull/26324 be performed in?

**Comment by jingyuanliang** [comment]
I can revoke the k8s bot's access if this one is coming in, so whether https://github.com/kubernetes/test-infra/pull/26324 is merged or not doesn't make a difference.

**Comment by chaodaiG** [comment]
> What order should this and [kubernetes/test-infra#26324](https://github.com/kubernetes/test-infra/pull/26324) be performed in?

it probably doesn't really matter, these plugins could co-exist

**Comment by chaodaiG** [comment]
/lgtm
/approve

/hold
Please make sure that the prow app is installed as https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/oss/onboarding.md#config-permission-for-prow

**Pull request merged**
