### PR TITLE
Add build cluster kubeconfig for looker-32

### PR DESCRIPTION
**Pull request by 2nd-half**
Please submit this change after the previous PR was submitted and postsubmit job succeeded.
Prow oncall: please don't submit this change until the secret is created successfully, which will be indicated by prow alerts in 2 minutes after the postsubmit job.

### CODE REVIEW

**Comment by listx** [comment]
@2nd-half Fix conflicts please?

**Review by chaodaiG — CHANGES_REQUESTED** [review]
/hold

The merge conflict was not resolved properly

**Comment by chaodaiG** [comment]
@2nd-half , an easier option might be rerun the script, skip steps other than PR creation part

**Comment by 2nd-half** [comment]
Ok, looks like I need to delete those branches first.

**Pull request closed without merging**
