### PR TITLE
Configure cherrypicker plugin for Knative Prow

### PR DESCRIPTION
**Pull request by chizhg**
Configure cherrypicker plugin for Knative Prow

Fixes: https://github.com/knative/test-infra/issues/2536

### CODE REVIEW

**Comment by chizhg** [comment]
/cc @n3wscott @chaodaiG 
FYI @mattmoor @dprotaso @vaikas

**Comment by chaodaiG** [comment]
This uses the default service account, which is generally not preferable as it's very powerful. Any chance it can use a dedicated service account with certain RBAC permissions?

**Comment by chizhg** [comment]
> This uses the default service account, which is generally not preferable as it's very powerful. Any chance it can use a dedicated service account with certain RBAC permissions?

Hmm I did a quick search, in https://stackoverflow.com/questions/52995962/kubernetes-namespace-default-service-account#:~:text=By%20default%2C%20the%20default%20service,appropriate%20permissions%20to%20do%20that. it said `By default, the default service account in a namespace has no permissions other than those of an unauthenticated user.`, so it should be fine to use the default service account?

**Comment by chaodaiG** [comment]
> > This uses the default service account, which is generally not preferable as it's very powerful. Any chance it can use a dedicated service account with certain RBAC permissions?
> 
> Hmm I did a quick search, in https://stackoverflow.com/questions/52995962/kubernetes-namespace-default-service-account#:~:text=By%20default%2C%20the%20default%20service,appropriate%20permissions%20to%20do%20that. it said `By default, the default service account in a namespace has no permissions other than those of an unauthenticated user.`, so it should be fine to use the default service account?

That's what I assumed as well, but it seemed not the case in prow. For example https://github.com/istio/test-infra/blob/master/prow/cluster/sinker_deployment.yaml, istio prow/sinker uses default service account, but it apparently needs pod deletion permission at least

**Comment by chizhg** [comment]
> > > This uses the default service account, which is generally not preferable as it's very powerful. Any chance it can use a dedicated service account with certain RBAC permissions?
> > 
> > 
> > Hmm I did a quick search, in https://stackoverflow.com/questions/52995962/kubernetes-namespace-default-service-account#:~:text=By%20default%2C%20the%20default%20service,appropriate%20permissions%20to%20do%20that. it said `By default, the default service account in a namespace has no permissions other than those of an unauthenticated user.`, so it should be fine to use the default service account?
> 
> That's what I assumed as well, but it seemed not the case in prow. For example https://github.com/istio/test-infra/blob/master/prow/cluster/sinker_deployment.yaml, istio prow/sinker uses default service account, but it apparently needs pod deletion permission at least

In the sinker case, I think it connects to the Prow and build clusters via `kubeconfig` - https://github.com/istio/test-infra/blob/master/prow/cluster/sinker_deployment.yaml#L22, which grants it super power on the `test-pods` namespace of these clusters.

**Comment by chaodaiG** [comment]
> > > > This uses the default service account, which is generally not preferable as it's very powerful. Any chance it can use a dedicated service account with certain RBAC permissions?
> > > 
> > > 
> > > Hmm I did a quick search, in https://stackoverflow.com/questions/52995962/kubernetes-namespace-default-service-account#:~:text=By%20default%2C%20the%20default%20service,appropriate%20permissions%20to%20do%20that. it said `By default, the default service account in a namespace has no permissions other than those of an unauthenticated user.`, so it should be fine to use the default service account?
> > 
> > 
> > That's what I assumed as well, but it seemed not the case in prow. For example https://github.com/istio/test-infra/blob/master/prow/cluster/sinker_deployment.yaml, istio prow/sinker uses default service account, but it apparently needs pod deletion permission at least
> 
> In the sinker case, I think it connects to the Prow and build clusters via `kubeconfig` - https://github.com/istio/test-infra/blob/master/prow/cluster/sinker_deployment.yaml#L22, which grants it super power on the `test-pods` namespace of these clusters.

Not the prow control plane cluster though, I don't think `kubeconfig` contains prow control plane cluster secret

**Comment by chizhg** [comment]
> > > > > This uses the default service account, which is generally not preferable as it's very powerful. Any chance it can use a dedicated service account with certain RBAC permissions?
> > > > 
> > > > 
> > > > Hmm I did a quick search, in https://stackoverflow.com/questions/52995962/kubernetes-namespace-default-service-account#:~:text=By%20default%2C%20the%20default%20service,appropriate%20permissions%20to%20do%20that. it said `By default, the default service account in a namespace has no permissions other than those of an unauthenticated user.`, so it should be fine to use the default service account?
> > > 
> > > 
> > > That's what I assumed as well, but it seemed not the case in prow. For example https://github.com/istio/test-infra/blob/master/prow/cluster/sinker_deployment.yaml, istio prow/sinker uses default service account, but it apparently needs pod deletion permission at least
> > 
> > 
> > In the sinker case, I think it connects to the Prow and build clusters via `kubeconfig` - https://github.com/istio/test-infra/blob/master/prow/cluster/sinker_deployment.yaml#L22, which grants it super power on the `test-pods` namespace of these clusters.
> 
> Not the prow control plane cluster though, I don't think `kubeconfig` contains prow control plane cluster secret

I'm not sure how Istio Prow cluster was setup, but none of its deployments are using fine-grained service account:
- https://github.com/istio/test-infra/blob/master/prow/cluster/hook_deployment.yaml#L21
- https://github.com/istio/test-infra/blob/master/prow/cluster/horologium_deployment.yaml

Maybe worth to dig it through how it works, but since Knative Prow is using the dedicated service account for each deployment - https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/knative/cluster/400-sinker.yaml#L29, I don't think it's a big problem to use the default service account here.

**Comment by chaodaiG** [comment]
sgtm
/lgtm

**Comment by chizhg** [comment]
Hmm.. `tide Pending — Not mergeable.`

**Pull request merged**
