### PR TITLE
Migrate Kubeflow from k8s-prow

### PR DESCRIPTION
**Pull request by clarketm**
Copied `kubeflow` configuration from [config](https://github.com/kubernetes/test-infra/blob/master/config/prow/config.yaml) and [plugins](https://github.com/kubernetes/test-infra/blob/master/config/prow/plugins.yaml) and add [**tide**](https://github.com/GoogleCloudPlatform/oss-test-infra/pull/192) and [**jobs**](https://github.com/GoogleCloudPlatform/oss-test-infra/pull/93).

### CODE REVIEW

**Comment by cjwagner** [comment]
Needed before this can merge:
- [ ] Give @google-oss-robot admin access to the Kubeflow org.
- [ ] Configure webhooks from the Kubeflow org to be sent to this Prow instance.
- [ ] Copy ProwJob configs from https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubeflow (We need to do this before enabling Tide so that Tide knows all the merge requirements.)
- [ ] Disable Tide and plugins for the Kubeflow org on the prow.k8s.io instance to avoid conflict/duplication.

Should be done soon (ideally before this merges as well):
- [ ] Copy pre-existing job results to the `oss-prow` GCS bucket.
- [ ] Replace TestGrid dashboards.

This is all I can think of off the top of my head. Lets keep track of all the steps we take so we can leave a guide for transferring service of an org from one Prow instance to another.

**Comment by jlewi** [comment]
I invited google-oss-robot to the kubeflow org; once the invite is accepted the bot should have write access to Kubeflow repositories
   * Is admin permissions really needed? I'm giving the google-oss-robot the same permissions as k8s-ci-robot so unless something changed hopefully that's sufficient.

What's the URL to use for these webhooks?


Related to: kubernetes/test-infra#14343.

**Comment by clarketm** [comment]
@cjwagner 
> * [x]  Copy ProwJob configs from https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubeflow (We need to do this before enabling Tide so that Tide knows all the merge requirements.), #93

Paradoxically, the jobs (more specifically `checkconfig`) needs the `trigger` plugin configured.

https://storage.googleapis.com/oss-prow/pr-logs/pull/GoogleCloudPlatform_oss-test-infra/93/pull-prow-config-validate/1201922395468730368/build-log.txt

**Comment by cjwagner** [comment]
> Paradoxically, the jobs (more specifically `checkconfig`) needs the `trigger` plugin configured for `kubeflow`.

You can add the jobs in this PR as well or wait to enable Tide until the jobs are added (trigger > jobs > tide).

**Comment by jlewi** [comment]
Related to: 

kubeflow/testing#475 - Kubeflow issue tracking migration to GoogleCloud Prow
 kubernetes/test-infra#14343 - Migrate Kubeflow to GoogleCloudProw

**Comment by jlewi** [comment]
google-oss-robot is now a member of the kubeflow GitHub org.

/lgm

@fejta @clarketm what is blocking this PR? Does  GoogleCloudPlatform/oss-test-infra#93 need to be merged first?

**Comment by clarketm** [comment]
> @fejta @clarketm what is blocking this PR? Does #93 need to be merged first?

@jlewi - Apologies for the latency; I have been supporting the Istio 1.4.2 release which went out today. I need to sync with @cjwagner to disambiguate his last comment.

> You can add the jobs in this PR as well or wait to enable Tide until the jobs are added (trigger > jobs > tide).

@cjwagner - if I opt to go for the latter (i.e. *wait to enable Tide*) does this just mean I can just omit the Tide-*specific* changes from this PR and reintroduce them in a PR after the jobs are merged: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/93

**Comment by clarketm** [comment]
@cjwagner
I disabled the `tide` configuration as requested. Is this now safe to merge?

**Comment by clarketm** [comment]
@fejta / @cjwagner 
I have all the required PRs. Please advise on the order and rollout strategy (either written or via this document: https://docs.google.com/document/d/127tZg2T3_oVHCnCkAqC_zTNOgChV7EN_e1fj4bet3V4/edit). Additionally, I need to coordinate a time to do this with @jlewi.

- [ ] https://github.com/GoogleCloudPlatform/oss-test-infra/pull/177
- [ ] https://github.com/GoogleCloudPlatform/oss-test-infra/pull/93
- [ ] https://github.com/GoogleCloudPlatform/oss-test-infra/pull/192
- [ ] https://github.com/kubernetes/test-infra/pull/15607

**Comment by jlewi** [comment]
@clarketm is there anything blocking this PR? Are you just waiting on confirmation from me or the Kubeflow build copy (@richardsliu )?

My expectation is this PR won't actually cause any downtime so its safe to merge.
Downtime should also be fine just coordinate with @richardsliu

**Comment by jlewi** [comment]
@clarketm Any update? We will be cutting our 1.0 release around mid january. It would be great to complete the test migration either this week or next; or else wait until after 1.0 is done to avoid instability in our test infra.

**Comment by clarketm** [comment]
@googlebot I consent

**Comment by clarketm** [comment]
@googlebot I consent

**Comment by clarketm** [comment]
> @clarketm: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-prow-config-validate	[605582e](https://github.com/GoogleCloudPlatform/oss-test-infra/commit/605582ed81d9ac3146ddc68dd14b55bc84e7f271)	[link](https://oss-prow.knative.dev/view/gcs/oss-prow/pr-logs/pull/GoogleCloudPlatform_oss-test-infra/177/pull-prow-config-validate/1235676418612924418)	`/test pull-prow-config-validate`

This is a warning not an error? So I disabled it in checkconfig.

**Comment by scottilee** [comment]
@googlebot I consent

**Comment by fejta** [comment]
I think someone from kubeflow should do this review

**Comment by scottilee** [comment]
@jlewi can you take a look?

**Comment by jlewi** [comment]
/lgtm
/approve

Thanks @clarketm . My hunch is that some of our more recent changes to our prow jobs may need to be ported over. I think we can do that after this PR is merged though.

When this PR is merged; will our tests be running simultaneously on the GCP prow instance as well as the K8s instance? Can we have some transition period during which we verify everything is working correctly on the new GCP instance before turning down the K8s instance?

**Comment by clarketm** [comment]
Replaced by: https://github.com/kubernetes/test-infra/pull/16898

**Pull request closed without merging**
