### PR TITLE
OSS prow: upgrade prometheus operator from 0.29.0 to 0.45.0

### PR DESCRIPTION
**Pull request by chaodaiG**
This was based on https://github.com/kubernetes/test-infra/pull/21291

### CODE REVIEW

**Comment by chaodaiG** [comment]
Thank you @mpherman2 , unfortunately I forgot to add CRDs in previous commit. Added them now, please take another look.

/cc @cjwagner 
For another pair of eyes

**Review by cjwagner — APPROVED** [review]
/hold

**Pull request merged**
