### PR TITLE
Add GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp Prow job

### PR DESCRIPTION
**Pull request by colinman**
Part of onboarding Secret Manager CSI Driver as part of https://github.com/GoogleCloudPlatform/oss-test-infra/issues/474

### CODE REVIEW

**Review by tam7t — APPROVED** [review]

**Review by e-blackwelder — APPROVED** [review]
I noticed you're using `GOOGLE_APPLICATION_CREDENTIALS` -- I think the term for that is something like "service account secrets/keys". While it works, workload identity is the preferred method of authenticating service accounts (for example, since workload identity doesn't use `secret` files, they can't be leaked accidentally). For an overview, see:
https://github.com/kubernetes/test-infra/tree/master/workload-identity#overview

To get workload identity working, you'll first need a (new) kubernetes service account, and then someone (probably the [test-infra oncaller](https://storage.googleapis.com/test-infra-oncall/oncall.html) at the time) will help you bind the cloud and kubernetes accounts -- as per the doc. Feel free to reach out!

For now though, this change looks fine.

**Pull request merged**
