### PR TITLE
Revert "Revert "Use workload identity for esp-v2 jobs""

### PR DESCRIPTION
**Pull request by TAOXUY**
This reverts commit 1523be8563657692fbf543f28289b9861b2c3869.

### CODE REVIEW

**Comment by BenTheElder** [comment]
Can you please add `OWNERS` to `prow/prowjobs/GoogleCloudPlatform/esp-v2` so your team can own your jobs?
I don't know anything about this particular job setup and I'm unsure if this is a correct change.

I asked within OSP EngProd and got no consensus so far :/

**Comment by TAOXUY** [comment]
https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/GoogleCloudPlatform/esp-v2/OWNERS
It's already been there but it doesn't work. My teammates' LGTM is useless.

**Comment by BenTheElder** [comment]
asking about that :/

**Comment by michelle192837** [comment]
@TAOXUY, can you have a teammate try LGTMing again? Hopefully should work now.

**Comment by TAOXUY** [comment]
Look like it works @michelle192837 @BenTheElder  Thansk!

**Pull request merged**
