### PR TITLE
Convert all existing webhooks to be managed by hmac tool

### PR DESCRIPTION
**Pull request by chaodaiG**

### CODE REVIEW

**Comment by chaodaiG** [comment]
Inspected all jobs by:
```
function jobsForConfig() {
  pre=( $(yq -r ".presubmits | keys[]" "${1}" 2>/dev/null) )
  post=( $(yq -r ".postsubmits | keys[]" "${1}" 2>/dev/null) )
  printf '%s\n' "${pre[@]}" "${post[@]}" | sort
}

for f in $(find ./prow/prowjobs -type f); do
    jobsForConfig $f
done
```

And got:
```
grpc-ecosystem/grpc-httpjson-transcoding
GoogleCloudPlatform/oss-test-infra
GoogleCloudPlatform/testgrid -
GoogleCloudPlatform/artifact-registry-apt-transport -
GoogleCloudPlatform/artifact-registry-yum-plugin -
GoogleCloudPlatform/guest-agent
GoogleCloudPlatform/guest-configs
GoogleCloudPlatform/guest-diskexpand
GoogleCloudPlatform/guest-logging-go
GoogleCloudPlatform/guest-oslogin
GoogleCloudPlatform/guest-test-infra
GoogleCloudPlatform/osconfig
GoogleCloudPlatform/compute-image-tools
GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp -
GoogleCloudPlatform/k8s-cloud-provider
GoogleCloudPlatform/esp-v2 -
google/http_pattern_matcher -
kubeflow/internal-acls -
kubeflow/gcp-blueprints -
kubeflow/website -
kubeflow/pipelines -
```
Note: `-` at the end of line means webhook already managed by hmac tool.

Plugins by `yq -r ".plugins | keys[]" ./prow/oss/plugins.yaml`:

```
GoogleCloudPlatform/artifact-registry-apt-transport
GoogleCloudPlatform/artifact-registry-yum-plugin
GoogleCloudPlatform/compute-image-tools
GoogleCloudPlatform/guest-agent
GoogleCloudPlatform/guest-configs
GoogleCloudPlatform/guest-diskexpand
GoogleCloudPlatform/guest-oslogin
GoogleCloudPlatform/guest-test-infra
GoogleCloudPlatform/osconfig
GoogleCloudPlatform/oss-test-infra
GoogleCloudPlatform/testgrid
googleforgames/agones *
grpc-ecosystem/grpc-httpjson-transcoding
kubeflow/community *
kubeflow/community-infra *
kubeflow/gcp-blueprints
kubeflow/internal-acls
kubeflow/pipelines
kubeflow/website
```
Note: `*` at end of line indicates repos don't have jobs yet

Repos in config.yaml all have jobs:

```
GoogleCloudPlatform/guest-agent
GoogleCloudPlatform/guest-configs
GoogleCloudPlatform/guest-diskexpand
GoogleCloudPlatform/guest-logging-go
GoogleCloudPlatform/guest-oslogin
GoogleCloudPlatform/guest-test-infra
GoogleCloudPlatform/osconfig
GoogleCloudPlatform/artifact-registry-apt-transport
GoogleCloudPlatform/artifact-registry-yum-plugin
GoogleCloudPlatform/oss-test-infra
GoogleCloudPlatform/testgrid
```

**Review by fejta — APPROVED** [review]
/hold

**Review by cjwagner — APPROVED** [review]

**Pull request merged**
