### PR TITLE
chore: Remove KFP presubmit SDK tests prow config

### PR DESCRIPTION
**Pull request by DharmitD**
As part of migration from Prow to GH Action Workflows for KFP, we have a PR proposed to migrate KFP SDK misc tests to a GHA: https://github.com/kubeflow/pipelines/pull/11037 

This PR removes KFP SDK tests from the prow config in parallel.

### CODE REVIEW

**Review by hbelmiro — APPROVED** [review]
LGTM

**Comment by hbelmiro** [comment]
cc @chensun

**Comment by chensun** [comment]
We should have the GHA migration done first before we can remove it from prow. Is it this PR: https://github.com/kubeflow/pipelines/pull/11037?

**Comment by hbelmiro** [comment]
> We should have the GHA migration done first before we can remove it from prow. Is it this PR: [kubeflow/pipelines#11037](https://github.com/kubeflow/pipelines/pull/11037)?

Yes.

**Review by chensun — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
