### PR TITLE
cleanup sharded prowjobs

### PR DESCRIPTION
**Pull request by sdowell**
The new prowjobs which use cluster pooling are running and stable. This cleans up the duplicate/legacy prowjobs.

### CODE REVIEW

**Comment by karlkfi** [comment]
You gonna manually delete the old test clusters afterwards?

**Comment by sdowell** [comment]
> You gonna manually delete the old test clusters afterwards?

Yeah the next step is to update the terraform to no longer provision clusters. I'll manually deprovision all of the legacy infra

**Review by karlkfi — APPROVED** [review]
/lgtm

**Review by michelle192837 — APPROVED** [review]

**Pull request merged**
