### PR TITLE
Migrate first Kubeflow presubmit test to oss prow

### PR DESCRIPTION
**Pull request by Bobgy**
Migrating the first presubmit test to verify the setup
/assign @chaodaiG

### CODE REVIEW

**Comment by chaodaiG** [comment]
/lgtm
/approve

/hold
In case you want to add an OWNERS file here

**Review by cjwagner — COMMENTED** [review]
LGTM, but +1 for adding an OWNERS file with at least 2 approvers.

**Comment by Bobgy** [comment]
Thanks, I'll add OWNERS after my teammates requests to join the org.

**Comment by Bobgy** [comment]
let's wait for them to join the org

**Comment by Bobgy** [comment]
Updated, let's start with these people and add more later

**Review by cjwagner — APPROVED** [review]

**Review by chaodaiG — APPROVED** [review]

**Pull request merged**
