### PR TITLE
YAML cleanup: consistent indentation before list elements

### PR DESCRIPTION
**Pull request by chaodaiG**
There is a mix of indent exist/not before yaml list elements, make them consistent by removing the indentation

### CODE REVIEW

**Comment by chaodaiG** [comment]
Cosmetic changes only

**Comment by spiffxp** [comment]
was there a formatter you used for this? curious what the settings were, perhaps we can enforce them with a presubmit

**Comment by chaodaiG** [comment]
Had tried formatter in my IDE and no matter what setting I use, they just insist:
```
foo:
  - bar
```
Over
```
foo:
- bar
```

Would be super glad if I can use a formatter to do this :(

Also, the yaml linter I have found are all happy with both scenarios above, didn't figure out how to enforce one over the other

**Comment by spiffxp** [comment]
https://stackoverflow.com/questions/30642317/how-to-automatically-re-indent-a-yaml-file

`pip install ruaml.yaml.cmd` provides a `yaml` command which may help, but a quick run shows it wasn't happy with multiple documents in a single yaml file
```
$ yaml round-trip plank.yaml
Traceback (most recent call last):
  File "/Users/spiffxp/.virtualenv/bin/yaml", line 8, in <module>
    sys.exit(main())
  File "/Users/spiffxp/.virtualenv/lib/python3.8/site-packages/ruamel/yaml/cmd/__main__.py", line 213, in main
    sys.exit(n.run())
  File "/Users/spiffxp/.virtualenv/lib/python3.8/site-packages/ruamel/yaml/cmd/__main__.py", line 51, in run
    return self._args.func()
  File "/Users/spiffxp/.virtualenv/lib/python3.8/site-packages/ruamel/yaml/cmd/__main__.py", line 77, in rt
    return self._yaml.round_trip()
  File "/Users/spiffxp/.virtualenv/lib/python3.8/site-packages/ruamel/yaml/cmd/yaml_cmd.py", line 423, in round_trip
    e, w, stabilize, outp = self.round_trip_input(inp)
  File "/Users/spiffxp/.virtualenv/lib/python3.8/site-packages/ruamel/yaml/cmd/yaml_cmd.py", line 462, in round_trip_input
    outp = self.round_trip_single(inp)
  File "/Users/spiffxp/.virtualenv/lib/python3.8/site-packages/ruamel/yaml/cmd/yaml_cmd.py", line 486, in round_trip_single
    _, i2, b2 = load_yaml_guess_indent(inp)
  File "/Users/spiffxp/.virtualenv/lib/python3.8/site-packages/ruamel/yaml/util.py", line 120, in load_yaml_guess_indent
    return round_trip_load(yaml_str, **kw), indent, block_seq_indent
  File "/Users/spiffxp/.virtualenv/lib/python3.8/site-packages/ruamel/yaml/main.py", line 1016, in round_trip_load
    return load(stream, RoundTripLoader, version, preserve_quotes=preserve_quotes)
  File "/Users/spiffxp/.virtualenv/lib/python3.8/site-packages/ruamel/yaml/main.py", line 951, in load
    return loader._constructor.get_single_data()
  File "/Users/spiffxp/.virtualenv/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 111, in get_single_data
    node = self.composer.get_single_node()
  File "/Users/spiffxp/.virtualenv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 83, in get_single_node
    raise ComposerError(
ruamel.yaml.composer.ComposerError: expected a single document in the stream
  in "<unicode string>", line 2, column 1:
    apiVersion: apps/v1
    ^ (line: 2)
but found another document
  in "<unicode string>", line 49, column 1:
    ---
    ^ (line: 49)
```

ruamel.yaml's indent settings are pretty flexible and could probably accomplish what you want if it was wrapped in a script

**Review by spiffxp — APPROVED** [review]
/lgtm

**Pull request merged**
