### PR TITLE
Bump cert-manager to version 'v0.5.2' to pick up bug fixes.

### PR DESCRIPTION
**Pull request by cjwagner**
Woot PR number 1!
Corresponds to https://github.com/kubernetes/test-infra/pull/10813

/assign @krzyzacy

### CODE REVIEW

**Comment by cjwagner** [comment]
Looks like we need to enable webhooks for this repo and turn on some plugins.

**Comment by BenTheElder** [comment]
We definitely need to turn on welcome, cat, dog, pony, ... 👍

**Comment by chrislovecnm** [comment]
Yah I can merge, but actually do not have admin perms on the repo to put in the webhooks

**Comment by krzyzacy** [comment]
I think I've made all of you repo-admins :-)

**Pull request merged**
