### PR TITLE
Add knative prow configs

### PR DESCRIPTION
**Pull request by chaodaiG**
- Copy/paste knative prow deployments as well as build cluster deployments configs here, so that auto-bump is handled here
- Add Makefile for manual deployments
- Add README

Postsubmit updating job will be added in knative/test-infra repo later

### CODE REVIEW

**Comment by albertomilan** [comment]
There seems to be a typo in the folder structure name: **prow/knaitve**

**Comment by chaodaiG** [comment]
> There seems to be a typo in the folder structure name: **prow/knaitve**

Thanks, fixed and force pushed

**Pull request merged**
