### PR TITLE
Disable blunderbuss, remove self-approve.

### PR DESCRIPTION
**Pull request by mattmoor**
This is based on TOC discussion, and community poll:

 - blunderbuss: https://knative.slack.com/archives/C93E33SN8/p1613067143285100
 - self-approve: https://knative.slack.com/archives/C93E33SN8/p1613067186285400

/hold

### CODE REVIEW

**Review by chaodaiG — APPROVED** [review]

**Comment by mattmoor** [comment]
Weird, I copied this from Tekton 😅 

I'll dig a bit 🤦

**Comment by mattmoor** [comment]
Here's where I copied it from: https://github.com/tektoncd/plumbing/blob/5531b5289d06bc847d6fdc43444fb6e54c886518/prow/plugins.yaml#L18

**Comment by chaodaiG** [comment]
Tekton prow is pretty ancient imo, the prow images were from 2019: https://github.com/tektoncd/plumbing/blob/5531b5289d06bc847d6fdc43444fb6e54c886518/prow/prow.yaml

**Comment by chaodaiG** [comment]
See announcement here: https://github.com/kubernetes/test-infra/blob/master/prow/ANNOUNCEMENTS.md

```
January 7, 2019 implicit_self_approve will become require_self_approval in the second half of this year.
```

**Review by chaodaiG — APPROVED** [review]

**Pull request merged**
