### PR TITLE
knative build cluster: update external secret to 8.3.0

### PR DESCRIPTION
**Pull request by chaodaiG**
Updated following https://github.com/external-secrets/kubernetes-external-secrets#install-with-kubectl

fixes: https://github.com/GoogleCloudPlatform/oss-test-infra/issues/1061

### CODE REVIEW

**Comment by chaodaiG** [comment]
/cc @coryrc 
cc @ Siddhesh-Ghadi

**Comment by Siddhesh-Ghadi** [comment]
Any update on this PR? - @chaodaiG

**Comment by Siddhesh-Ghadi** [comment]
@coryrc - Could you help merge this PR? Thanks.

**Comment by coryrc** [comment]
Sorry, I was confused who was supposed to give an lgtm where, you should /assign to me!

/lgtm
/approve

**Pull request merged**
