### PR TITLE
Knative prow monitoring stack

### PR DESCRIPTION
**Pull request by chaodaiG**
This PR adds knative prow monitoring stack, which is basically copy/pasted from `./prow/oss/cluster/monitoring`. For easier code review, this PR has 3 commits:

1. Blind copy/paste
1. Delete `./prow/knative/cluster/monitoring/mixins/vendor` and make it reuse the one under `./prow/oss/cluster/monitoring`
1. Knative specific changes

### CODE REVIEW

**Comment by chaodaiG** [comment]
This PR hasn't been tested yet, creating it now just in case there is anything obvious that I missed in the PR and could be spotted by reviewer.

/hold

**Review by michelle192837 — APPROVED** [review]
Feel free to wait for other review, but assuming testing works this looks good to me!

**Comment by chaodaiG** [comment]
Thank you Michelle, I did try deploying this and the dashboard was up. The alerting was working too, but it's sending false alarms as knative prow wasn't set to send metrics to prometheus, I'll fix it

**Comment by chaodaiG** [comment]
Test deploy went well, the alerts issue is addressed separately in https://github.com/GoogleCloudPlatform/oss-test-infra/pull/566

I'll let this merge first
/unhold

**Pull request merged**
