### PR TITLE
Knative prow monitoring secret: updated with a script instead of make…

### PR DESCRIPTION
**Pull request by chaodaiG**
… rule

It's pretty hard to have make rules to exit based on wrapped subshell, turn it into a script and it should exit correctly

### CODE REVIEW

**Comment by chaodaiG** [comment]
/hold
The secret doesn't exist yet

**Review by cjwagner — APPROVED** [review]
The script is more readable too :+1:

**Comment by cjwagner** [comment]
> The secret doesn't exist yet

Should we remove the existing logic in a separate PR in the meantime or will the secret be exist soon?

**Comment by chaodaiG** [comment]
> > The secret doesn't exist yet
> 
> Should we remove the existing logic in a separate PR in the meantime or will the secret be exist soon?

They exist now :)
/unhold

**Pull request merged**
