### PR TITLE
Switch Prow components to use ghproxy.

### PR DESCRIPTION
**Pull request by cjwagner**
Depends on 
- [x] https://github.com/GoogleCloudPlatform/oss-test-infra/pull/344
- [x] validating that the proxy is working.

/hold
/assign fejta

### CODE REVIEW

**Comment by fejta** [comment]
https://oss-prow.knative.dev/view/gcs/oss-prow/logs/post-oss-test-infra-deploy-prow/1252733899251912704

**Comment by cjwagner** [comment]
Everything is deployed now and the cache appears to be working properly:
```
< X-Cache-Mode: REVALIDATED
```
This is ready to merge, but we should probably wait until tomorrow morning?

**Comment by fejta** [comment]
lgtm

**Pull request merged**
