### PR TITLE
En server: add an e2e test job, update entrypoint of smoke test

### PR DESCRIPTION
**Pull request by chaodaiG**

### CODE REVIEW

**Review by sethvargo — APPROVED** [review]
/lgtm

**Comment by sethvargo** [comment]
@chaodaiG looks like it's sad

**Comment by chaodaiG** [comment]
> @chaodaiG looks like it's sad

I think it's the indentation :(

**Comment by chaodaiG** [comment]
This test shouldn't take that long
/test pull-oss-test-infra-check-testgrid-config

**Comment by chaodaiG** [comment]
All passed now. @sethvargo , another lgtm please

**Pull request merged**
