### PR TITLE
Prow alert when images are stale for 14 days

### PR DESCRIPTION
**Pull request by chaodaiG**

### CODE REVIEW

**Review by fejta — APPROVED** [review]
/hold

**Review by cjwagner — CHANGES_REQUESTED** [review]
Please address the same comments as here: https://github.com/istio/test-infra/pull/3092

**Comment by chaodaiG** [comment]
> Please address the same comments as here: [istio/test-infra#3092](https://github.com/istio/test-infra/pull/3092)

Done

**Review by cjwagner — APPROVED** [review]

**Review by fejta — APPROVED** [review]

**Pull request merged**
