### PR TITLE
packagebuild for guest-agent and guest-oslogin

### PR DESCRIPTION
**Pull request by hopkiw**
add package builder presubmits for guest-agent and guest-oslogin repos

### CODE REVIEW

**Comment by hopkiw** [comment]
@fejta is there a reason this is on hold?

**Comment by clarketm** [comment]
> @fejta is there a reason this is on hold?

@hopkiw - @fejta is currently unavailable. I surmise it was held in order to verify that the secret(s) (e.g. `daisy-service-account`) are loaded in the cluster. If you are confident with the job changes, then you can unhold.

**Comment by hopkiw** [comment]
/hold cancel
clearly

**Pull request merged**
