### PR TITLE
decorate presubmit jobs

### PR DESCRIPTION
**Pull request by hopkiw**
this should add logging and spyglass/gubernator links

### CODE REVIEW

**Comment by krzyzacy** [comment]
@rofuentes - https://github.com/iamsubratp is not part of GCP org or your team (https://github.com/orgs/GoogleCloudPlatform/teams/compute-image-tools-admin)

**Comment by rofuentes** [comment]
@krzyzacy can you replace that team with https://github.com/orgs/GoogleCloudPlatform/teams/compute-image-writers

**Comment by krzyzacy** [comment]
@rofuentes - works now

**Pull request merged**
