### PR TITLE
Add build cluster kubeconfig for bms-oracle-team

### PR DESCRIPTION
**Pull request by jcnars**
Please submit this change after the previous PR was submitted and postsubmit job succeeded. Prow oncall: please don't submit this change until the secret is created successfully, which will be indicated by prow alerts in 2 minutes after the postsubmit job.

### CODE REVIEW

**Comment by jcnars** [comment]
/hold

wait for https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2057 to be merged

**Review by cjwagner — APPROVED** [review]
/hold

**Pull request merged**
